channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - lz4==4.3.2
  - numpy==1.26.4
  - packaging==23.2
  - pathlib==1.0.1
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
name: mlflow-env
